// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shuttle.Workflow.SqlServer;

#nullable disable

namespace Shuttle.Workflow.SqlServer.Migrations
{
    [DbContext(typeof(WorkflowDbContext))]
    [Migration("20260829114943_Initial_Migration")]
    partial class Initial_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("workflow")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shuttle.Workflow.SqlServer.Models.Process", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContinuationMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ContinuationRegisteredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ContinuationToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DateCompleted")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateRegistered")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeferredTill")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Key")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset?>("OverdueAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(130)
                        .HasColumnType("nvarchar(130)");

                    b.Property<string>("StatusMessage")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("Key", "DateCompleted")
                        .HasDatabaseName("IX_Process_Key_DateCompleted")
                        .HasFilter("[Key] IS NOT NULL");

                    b.HasIndex("Key", "Status")
                        .HasDatabaseName("IX_Process_Key_Status")
                        .HasFilter("[Key] IS NOT NULL");

                    b.ToTable("Process", "workflow");
                });

            modelBuilder.Entity("Shuttle.Workflow.SqlServer.Models.ProcessCommit", b =>
                {
                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTimeOffset>("DateCommitted")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ProcessId", "Key");

                    b.ToTable("ProcessCommit", "workflow");
                });

            modelBuilder.Entity("Shuttle.Workflow.SqlServer.Models.ProcessDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "IX_ProcessDefinition")
                        .IsUnique();

                    b.ToTable("ProcessDefinition", "workflow");
                });

            modelBuilder.Entity("Shuttle.Workflow.SqlServer.Models.ProcessDefinitionMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InvokeTimeout")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProcessDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ProcessDefinitionId", "TypeName", "SequenceNumber" }, "IX_ProcessDefinition")
                        .IsUnique();

                    b.ToTable("ProcessDefinitionMessage", "workflow");
                });

            modelBuilder.Entity("Shuttle.Workflow.SqlServer.Models.ProcessDefinitionStateItem", b =>
                {
                    b.Property<Guid>("ProcessDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(130)
                        .HasColumnType("nvarchar(130)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("ProcessDefinitionId", "Name");

                    b.ToTable("ProcessDefinitionStateItem", "workflow");
                });

            modelBuilder.Entity("Shuttle.Workflow.SqlServer.Models.ProcessMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DateCompleted")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateSent")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("InvokeTimeout")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ProcessId", "TypeName", "SequenceNumber" }, "IX_ProcessMessage")
                        .IsUnique();

                    b.ToTable("ProcessMessage", "workflow");
                });

            modelBuilder.Entity("Shuttle.Workflow.SqlServer.Models.ReferenceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(130)
                        .HasColumnType("nvarchar(130)");

                    b.Property<Guid>("ReferenceTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceTypeId");

                    b.ToTable("ReferenceItem", "workflow");
                });

            modelBuilder.Entity("Shuttle.Workflow.SqlServer.Models.ReferenceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(130)
                        .HasColumnType("nvarchar(130)");

                    b.HasKey("Id");

                    b.ToTable("ReferenceType", "workflow");
                });

            modelBuilder.Entity("Shuttle.Workflow.SqlServer.Models.Semaphore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateRegistered")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Key" }, "IX_Semaphore")
                        .IsUnique();

                    b.ToTable("Semaphore", "workflow");
                });

            modelBuilder.Entity("Shuttle.Workflow.SqlServer.Models.State", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Key" }, "IX_State")
                        .IsUnique();

                    b.ToTable("State", "workflow");
                });

            modelBuilder.Entity("Shuttle.Workflow.SqlServer.Models.StateItem", b =>
                {
                    b.Property<Guid>("StateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(130)
                        .HasColumnType("nvarchar(130)");

                    b.Property<DateTimeOffset>("EffectiveDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValue(new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));

                    b.Property<bool?>("BooleanValue")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("DateRegistered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("TODATETIMEOFFSET(SYSUTCDATETIME(), 0)");

                    b.Property<DateTimeOffset?>("DateTimeValue")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("DecimalValue")
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTimeOffset>("EffectiveDateEnd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValue(new DateTimeOffset(new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999), new TimeSpan(0, 0, 0, 0, 0)));

                    b.Property<Guid?>("GuidValue")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StringValue")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("StateId", "Name", "EffectiveDate");

                    b.ToTable("StateItem", "workflow");
                });

            modelBuilder.Entity("Shuttle.Workflow.SqlServer.Models.ProcessCommit", b =>
                {
                    b.HasOne("Shuttle.Workflow.SqlServer.Models.Process", null)
                        .WithMany("Commits")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shuttle.Workflow.SqlServer.Models.ProcessDefinitionMessage", b =>
                {
                    b.HasOne("Shuttle.Workflow.SqlServer.Models.ProcessDefinition", null)
                        .WithMany("Messages")
                        .HasForeignKey("ProcessDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shuttle.Workflow.SqlServer.Models.ProcessDefinitionStateItem", b =>
                {
                    b.HasOne("Shuttle.Workflow.SqlServer.Models.ProcessDefinition", null)
                        .WithMany("StateItems")
                        .HasForeignKey("ProcessDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shuttle.Workflow.SqlServer.Models.ProcessMessage", b =>
                {
                    b.HasOne("Shuttle.Workflow.SqlServer.Models.Process", null)
                        .WithMany("Messages")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shuttle.Workflow.SqlServer.Models.ReferenceItem", b =>
                {
                    b.HasOne("Shuttle.Workflow.SqlServer.Models.ReferenceType", null)
                        .WithMany("ReferenceItems")
                        .HasForeignKey("ReferenceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shuttle.Workflow.SqlServer.Models.StateItem", b =>
                {
                    b.HasOne("Shuttle.Workflow.SqlServer.Models.State", "State")
                        .WithMany("Items")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("Shuttle.Workflow.SqlServer.Models.Process", b =>
                {
                    b.Navigation("Commits");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Shuttle.Workflow.SqlServer.Models.ProcessDefinition", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("StateItems");
                });

            modelBuilder.Entity("Shuttle.Workflow.SqlServer.Models.ReferenceType", b =>
                {
                    b.Navigation("ReferenceItems");
                });

            modelBuilder.Entity("Shuttle.Workflow.SqlServer.Models.State", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
