<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UserSecretsId>26baf5f2-996f-42d0-afe2-717270132707</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
		<PackageReference Include="Microsoft.Data.SqlClient.Extensions.Azure" Version="7.0.2" />
		<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.11" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
		<PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
		<PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
		<PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
		<PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
		<PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
		<PackageReference Include="Shuttle.Hopper.AzureStorageQueues" Version="22.0.1" />
		<PackageReference Include="Shuttle.Hopper.Scheduling.Messages" Version="1.0.0" />
		<PackageReference Include="Shuttle.Pigeon.RestClient" Version="2.0.11" />
		<PackageReference Include="Shuttle.Recall.SqlServer.EventProcessing" Version="22.0.1" />
		<PackageReference Include="Shuttle.Recall.SqlServer.Storage" Version="22.0.1" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Shuttle.Workflow.Application\Shuttle.Workflow.Application.csproj" />
	  <ProjectReference Include="..\Shuttle.Workflow.EventProcessing\Shuttle.Workflow.EventProcessing.csproj" />
	  <ProjectReference Include="..\Shuttle.Workflow.Messages\Shuttle.Workflow.Messages.csproj" />
	  <ProjectReference Include="..\Shuttle.Workflow.SqlServer\Shuttle.Workflow.SqlServer.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="appsettings.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>