<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.12" />
    <PackageReference Include="Shuttle.Mediator" Version="21.0.2" />
    <PackageReference Include="Shuttle.Recall" Version="23.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shuttle.Workflow.Builder\Shuttle.Workflow.Builder.csproj" />
    <ProjectReference Include="..\Shuttle.Workflow.WebApi.Contracts\Shuttle.Workflow.WebApi.Contracts.csproj" />
    <ProjectReference Include="..\Shuttle.Workflow.SqlServer\Shuttle.Workflow.SqlServer.csproj" />
    <ProjectReference Include="..\Shuttle.Workflow\Shuttle.Workflow.csproj" />
  </ItemGroup>

</Project>
