<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UserSecretsId>36fc92f7-6bfa-43ec-b8ab-2b2994b494d3</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Properties\**" />
	  <EmbeddedResource Remove="Properties\**" />
	  <None Remove="Properties\**" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="appsettings.json" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include=".files\StateConditionalOptions.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Include="appsettings.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.12" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.12" />
		<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.12" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.0" />
		<PackageReference Include="Microsoft.OpenApi" Version="2.12.2" />
		<PackageReference Include="Moq" Version="4.20.72" />
		<PackageReference Include="NUnit" Version="4.6.1" />
		<PackageReference Include="NUnit3TestAdapter" Version="6.3.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Shuttle.Workflow.RestClient\Shuttle.Workflow.RestClient.csproj" />
	  <ProjectReference Include="..\Shuttle.Workflow.WebApi\Shuttle.Workflow.WebApi.csproj" />
	</ItemGroup>

</Project>